name: Node.js CI

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20  # You can specify your preferred Node.js version here

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build  # Replace with your build script if needed
